export const projects = [
    {
        id: 'nexus-ai',
        title: 'Nexus Core',
        category: 'IA',
        industry: 'Fintech',
        year: '2025',
        description: 'Infraestructura neuronal para procesamiento de datos en tiempo real.',
        challenge: 'Procesar 1M+ transacciones por segundo con latencia <10ms y detección de fraude en tiempo real.',
        solution: 'Arquitectura distribuida basada en Rust y TensorFlow, con optimización de hardware dedicado.',
        result: 'Reducción del 40% en falsos positivos y 99.99% de uptime en picos de tráfico.',
        image: '',
    },
    {
        id: 'strata-fintech',
        title: 'Strata Systems',
        category: 'Software',
        industry: 'Banca',
        year: '2024',
        description: 'Arquitectura de microservicios para banca de inversión global.',
        challenge: 'Modernizar un core bancario legacy sin interrumpir operaciones diarias.',
        solution: 'Patrón Strangler Fig para migración progresiva a microservicios en Go.',
        result: 'Despliegues diarios (vs mensuales) y reducción del 60% en costes de infraestructura.',
        image: '',
    },
    {
        id: 'aether-platform',
        title: 'Aether',
        category: 'Plataformas',
        industry: 'Energía',
        year: '2024',
        description: 'Ecosistema IoT para gestión energética industrial.',
        challenge: 'Unificar datos de miles de sensores heterogéneos en una plataforma coherente.',
        solution: 'Pipeline de datos en tiempo real con Apache Kafka y visualización en WebGL.',
        result: 'Optimización del 15% en consumo energético para clientes industriales.',
        image: '',
    },
    {
        id: 'vertex-logic',
        title: 'Vertex Logic',
        category: 'Software',
        industry: 'Logística',
        year: '2023',
        description: 'Sistema de optimización logística predictiva.',
        challenge: 'Rutas ineficientes causando pérdidas millonarias en combustible.',
        solution: 'Algoritmos genéticos para ruteo dinámico considerando tráfico y clima.',
        result: '20% de ahorro en combustible y mejora del 30% en tiempos de entrega.',
        image: '',
    }
];
